repos:
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [ "--line-length", "120" ]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
        args: [ "--max-line-length", "120" ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black", "--line-length", "120" ]
        exclude: migrations/
